import { chromium } from 'playwright';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const extension=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const root=path.resolve(process.env.IDEA_FLOW_TEST_OUTPUT || path.join(extension,'evaluation/local-browser'));
if (!process.env.OPENROUTER_KEY_FILE) throw new Error('Set OPENROUTER_KEY_FILE to an existing key file. This test makes a small number of paid requests.');
await fs.mkdir(root,{recursive:true});
const profile=await fs.mkdtemp(path.join(os.tmpdir(),'idea-flow-live-'));
const context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,args:['--disable-extensions-except='+extension,'--load-extension='+extension],viewport:{width:1440,height:1100}});
const log=[];
const record=(name,detail={})=>{log.push({name,passed:true,...detail});console.log(JSON.stringify(log.at(-1)))};
const errors=[];
try{
 const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker',{timeout:15000});
 const id=new URL(worker.url()).host;
 const settings=await context.newPage();await settings.goto('chrome-extension://'+id+'/src/options.html');
 await settings.evaluate(()=>chrome.runtime.sendMessage({type:'SAVE_SETTINGS',removeKey:true}));
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message.slice(0,300)));
 await page.goto('https://www.youtube.com/results?search_query=guitar+barre+chord+buzzing+fix',{waitUntil:'domcontentloaded'});
 const ui=page.locator('#idea-flow-root');await ui.waitFor({state:'attached',timeout:20000});
 await page.waitForFunction(()=>document.querySelector('#idea-flow-root')?.shadowRoot.querySelector('#status-text').textContent.includes('Add your OpenRouter'));
 assert.equal(await page.locator('.idea-flow-collapsed').count(),0);record('missing_key_fail_open');
 const other=await context.newPage();await other.goto('https://example.com');assert.equal(await other.locator('#idea-flow-root').count(),0);record('no_injection_outside_youtube');await other.close();
 const key=(await fs.readFile(process.env.OPENROUTER_KEY_FILE,'utf8')).trim();
 await settings.locator('#api-key').fill(key);await settings.locator('#save-key').click();await settings.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Key saved'));
 assert.equal(await settings.locator('#api-key').inputValue(),'');record('byok_save_clears_input');
 await page.bringToFront();await page.reload({waitUntil:'domcontentloaded'});await ui.waitFor({state:'attached'});
 await ui.locator('#goal').fill('Fix a hydration mismatch error in a Next.js App Router application.');await ui.getByRole('button',{name:'Set goal',exact:true}).click();
 await page.waitForSelector('.idea-flow-placeholder',{timeout:60000});
 const hiddenBefore=await page.locator('.idea-flow-collapsed').count();record('real_jev_collapses_obvious_wrong_topic',{collapsed:hiddenBefore});
 await page.screenshot({path:path.join(root,'live-filtered.png')});
 await page.locator('.idea-flow-placeholder').first().getByRole('button',{name:'Save for later'}).click();
 await page.waitForFunction(()=>document.querySelector('#idea-flow-root').shadowRoot.querySelector('#saved').textContent.includes('('));record('save_tangent');
 await page.locator('.idea-flow-placeholder').first().getByRole('button',{name:'Reveal video',exact:true}).click();assert.ok(await page.locator('.idea-flow-badge').count()>0);record('reveal_one');
 await ui.locator('#tangents').click();await page.waitForFunction(()=>document.querySelectorAll('.idea-flow-collapsed').length===0);record('reveal_all');
 await ui.locator('#tangents').click();await ui.locator('#pause').click();await page.waitForFunction(()=>document.querySelectorAll('.idea-flow-collapsed').length===0);record('pause_restores_all');
 await ui.locator('#goal').fill('Stop strings buzzing or sounding muted when I play barre chords on guitar.');await ui.getByRole('button',{name:'Set goal',exact:true}).click();
 await page.waitForSelector('.idea-flow-direct,.idea-flow-background',{timeout:60000});record('goal_change_reclassifies_same_page');
 const search=page.locator('input[name="search_query"]').first();await search.fill('guitar barre chord finger placement');await search.press('Enter');await page.waitForURL('**/results?search_query=guitar+barre+chord+finger+placement*',{timeout:20000});
 await page.waitForTimeout(1500);assert.equal(await ui.locator('#goal').inputValue(),'Stop strings buzzing or sounding muted when I play barre chords on guitar.');record('youtube_spa_navigation_preserves_goal');
 const first=page.locator('ytd-video-renderer a#video-title').first();const url=await first.getAttribute('href');await page.goto('https://www.youtube.com'+url,{waitUntil:'domcontentloaded'});await ui.waitFor({state:'attached'});
 await page.waitForFunction(()=>document.querySelector('ytd-watch-metadata h1')?.textContent.trim(),{timeout:20000});
 await page.evaluate(()=>{const v=document.querySelector('video');if(v){v.pause();try{v.currentTime=37}catch{}}});
 await ui.locator('#save-video').click();await page.waitForFunction(()=>document.querySelector('#idea-flow-root').shadowRoot.querySelector('#save-video').textContent==='Video saved');assert.equal(await ui.locator('#pause').textContent(),'Pause filtering');record('save_video_preserves_filtering');await ui.locator('#pause').click();await page.waitForFunction(()=>document.querySelector('#idea-flow-root').shadowRoot.querySelector('#pause').textContent==='Resume filtering');
 await settings.reload();const state=await settings.evaluate(()=>chrome.runtime.sendMessage({type:'GET_STATE'}));assert.equal(state.active,false);assert.ok(state.saved.some(v=>Number.isFinite(v.timestamp)&&v.url.includes('t=')));assert.equal('key' in state,false);record('saved_playback_position_and_key_isolation',{saved:state.saved.length,usage:state.usage});
 await settings.screenshot({path:path.join(root,'settings-ready.png')});
 assert.equal(errors.length,0);record('page_script_error_check',{errors});
}catch(e){log.push({name:'live_run',passed:false,error:e.message});console.log(JSON.stringify(log.at(-1)));process.exitCode=1;}
finally{await fs.writeFile(path.join(root,'live-extension-results.json'),JSON.stringify(log,null,2));await context.close();await fs.rm(profile,{recursive:true,force:true});}
